# .pre-commit-config.yaml
# for details see https://pre-commit.com
# for list of available hooks see https://pre-commit.com/hooks.html

fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
   - id: detect-aws-credentials
     args: ['--allow-missing-credentials']
   - id: detect-private-key
   - id: check-added-large-files
     args: ['--maxkb=200']
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
   - id: black
     args: ['--check', '--diff']
- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
   - id: flake8
     args: [--max-line-length=120,  --ignore=E203]
