name: Deploy Sphinx docs static content to GitHub Pages
# Reference for publishing github pages
# https://docs.github.com/en/pages/getting-started-with-github-pages
# Note: This workflow publishes with a GitHub Action, and not pushing to a branch.

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: pages-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  # Single build and deploy job
  docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r docs/requirements.txt .
      - name: Build Sphinx Documentation
        run: |
          make -C docs html BUILDDIR=build
          rm docs/build/html/.buildinfo

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: sphinx-docs
          path: docs/build/html

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload build sphinx docs
          path: 'docs/build/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
